### ISSUE TITLE
catch_haul_cruises not found

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [EmilyMarkowitz-NOAA/gap_public_data#1]
I was running the `run.R` script and could go further than line 36. I got this error:
![image](https://user-images.githubusercontent.com/73858992/166324131-0a7cdf86-d517-404b-ab51-20c982233fa9.png)

I ran the `data.dl` script with my Oracle credentials and then started `run.R`.

I would troubleshoot more intensely but I don't have tons of time rn and this seems like something you'll know faster than I! I want to run your code to get cpue tables for some of our overlapping species and compare them to the outputs from my code and the tables in RACEBASE/GOA.

Thanks!

**Comment by EmilyMarkowitz-NOAA** [comment]
Yep - I see how this would happen. 2 things: 

1) I had updated the code (`source('./code/find_itis_species_codes.R')`) so we could collect ITIS and WoRMS codes using {taxize} but it's pretty time intensive, so I added some code (`taxize0 <- FALSE`; #[d691d14](https://github.com/afsc-gap-products/gap_public_data/commit/d691d1419c672415575eae65bcd38a3b68eecb61)) so you don't have to run that. Does it work for you now? 

2) I also emailed you with some google links to data you'll need that you can't get on oracle yet (working on that separately).

**Comment by MargaretSiple-NOAA** [comment]
Yeah, same error as before. I think the issue is that `catch_haul_cruises` uses `tax_conf`, which doesn't exist if you haven't built the taxonomic confidence table. I made some tiny edits to `data.R` and `analysis.R` that only build the taxonomic confidence column if it's in there in the first place (i.e., if `taxize0=TRUE`). Take em or leave em! But this solves my problem.
