### ISSUE TITLE
survey years included could be revised

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [EmilyMarkowitz-NOAA/gap_public_data#10]
@EmilyMarkowitz-NOAA GOA data in FOSS tables in Oracle only include data from 1993 onward.  I think we should include data from 1990 onward, unless @Ned-Laman-NOAA thinks there is good reason to stick with this cutoff.  We know there were some ID issues in these years, but I think it makes sense to exclude only the 1980s data due to lack of standardization.

I checked the years included for the other surveys and they seem good.  I noticed that the reduced 2018 NBS survey is included, so we leave that in we should make sure the uniqueness of this year is emphasized.

**Comment by EmilyMarkowitz-NOAA** [comment]
Happy to add the 1990 GOA survey in if @Ned-Laman-NOAA thinks we should, but we did have some fairly [extensive discussions](https://github.com/afsc-gap-products/gap_public_data/blob/main/code/data.R#L100) about only including data from and after 1991. 

Thanks for alerting me that the 2018 data are in the data. Is this the new data on oracle or the data currently on FOSS? It shouldn't be there, so I'll remove it.

**Comment by Lewis-Barnett-NOAA** [comment]
Thanks Emily.  No worries if that was already discussed and decided regarding the GOA data.

The 2018 NBS data were in the data on oracle...not sure about FOSS/web interface

**Comment by Ned-Laman-NOAA** [comment]
For better or worse, the 1991 cutoff is what we've been using, communicating to stock assessment, and justifying for many years. Someone could do some analyses and come up with new justification for including <1991 cruises, but I'd hesitate to roll the clock back on that decision without some justification.

**Comment by EmilyMarkowitz-NOAA** [comment]
## 2018 NBS data
I looked through the data currently in the oracle schema and couldn't find 2018 NBS data in there. Can you share the query or a screenshot of what you saw, @Lewis-Barnett-NOAA? I wonder if you mistook 2018 EBS survey data for 2018 NBS data.

Here is the SQL query I tried (Note that startum 81, 71, and 70 = NBS) and both returned 0 results: 
```
SELECT YEAR, SRVY, STRATUM
FROM FOSS_CPUE_ZEROFILLED
WHERE YEAR = 2018
AND STRATUM IN (81, 71, 70);

SELECT YEAR, SURVEY, STRATUM
FROM JOIN_FOSS_CPUE_HAUL
WHERE YEAR = 2018
AND STRATUM IN (81, 71, 70);
```

## 1990 GOA data
re: @Ned-Laman-NOAA's last comment, I suppose @Lewis-Barnett-NOAA could add a request to assess if we can add 1990 GOA data back as `abundance_haul = "Y"` in the [data-request github repo](https://github.com/afsc-gap-products/data-requests). Maybe it is something that can be checked as part of the new [AFSC.GAP.DBE/design-based-indices R Package](https://github.com/afsc-gap-products/design-based-indices)?

**Comment by EmilyMarkowitz-NOAA** [comment]
re: @Ned-Laman-NOAA's last comment, I suppose you, @Lewis-Barnett-NOAA, if you want it to be checked out, could add a request to assess if we can add 1990 GOA data back as `abundance_haul = "Y"` in the [data-request github repo](https://github.com/afsc-gap-products/data-requests). Maybe it is something that can be checked as part of the new [AFSC.GAP.DBE/design-based-indices R Package](https://github.com/afsc-gap-products/design-based-indices)?

**Comment by Lewis-Barnett-NOAA** [comment]
Ah, you're probably right about the 2018 data.  I double checked and the 2018 NBS data are not included.  Thanks.

I've started a sidebar about the 1990 GOA data and will follow up accordingly.
