### ISSUE TITLE
Make a better API pull process

### ISSUE THREAD

**Issue by EmilyMarkowitz-NOAA** [EmilyMarkowitz-NOAA/gap_public_data#12]
### Currently, we can use a variation on the [following code](https://github.com/afsc-gap-products/gap_public_data#connect-to-the-api-with-r) to pull data, but it could be easier to use and pull more data each pull. 

**Approach 1: work on the partially built `{fossAPI}` R package:** 

It would be great to develop a clean, easy way to pull data from the FOSS data platform, like [Alex Richardson's partially built FOSS API pull package](https://github.com/AlexRichardson-NOAA/fossAPI). 

API R packages that are already being used for other data streams that could be an example for our needs
- [rCAX](https://github.com/nwfsc-math-bio/rCAX)
- [https://github.com/nmfs-fish-tools/projectstats](projectstats)
- [fredr](https://cran.r-project.org/web/packages/fredr/vignettes/fredr.html)
- [rredlist](https://github.com/ropensci/rredlist/tree/master/R)
- [rnoaa](https://docs.ropensci.org/rnoaa/)

**Approach 2: loop through data content:** 
To loop through data from an API, you want to set up a loop that exits when the api call returns `hasMore = false`. In the loop, you will adjust your offset (e.g. offset = offset + limit), make another api call, then append the returned items to an items variable.

If you look at the output from https://apps-st.fisheries.noaa.gov/ods/foss/afsc_groundfish_survey/ you'll see the following. `hasMore` tells you there is more data. `offset` tells the API where to start to retrieve the next page of data. 
```
"hasMore": true,
"limit": 25,
"offset": 0,
"count": 25,
```
So to get the next page of data, set `offset = 25` (e.g., https://apps-st.fisheries.noaa.gov/ods/foss/afsc_groundfish_survey/?offset=25). Also notice that there's a links section that tells you what the next page of data says `offset = 50`. In your code, instead of having to keep track of what record you're on, you can just use the element 5 from the links array to request the next chunk of data.
```
"links": [
{
"rel": "self",
"href": "https://apps-st.fisheries.noaa.gov/ods/foss/afsc_groundfish_survey/"
},
{
"rel": "edit",
"href": "https://apps-st.fisheries.noaa.gov/ods/foss/afsc_groundfish_survey/"
},
{
"rel": "describedby",
"href": "https://apps-st.fisheries.noaa.gov/ods/foss/metadata-catalog/afsc_groundfish_survey/"
},
{
"rel": "first",
"href": "https://apps-st.fisheries.noaa.gov/ods/foss/afsc_groundfish_survey/"
},
{
"rel": "next",
"href": "https://apps-st.fisheries.noaa.gov/ods/foss/afsc_groundfish_survey/?offset=50"
},
{
"rel": "prev",
"href": "https://apps-st.fisheries.noaa.gov/ods/foss/afsc_groundfish_survey/"
}
]
```

cc'ing @Lewis-Barnett-NOAA and @MargaretSiple-NOAA, who would also be interested in this development.

**Comment by Lewis-Barnett-NOAA** [comment]
The code and guidance for using the API or other examples of ways of accessing the data with R is now gone from the readme page (this link doesn't exist- https://github.com/afsc-gap-products/gap_public_data#connect-to-the-api-with-r).  Can we reinstate that or is defunct now?

More broadly though, we do need to improve this, thanks @EmilyMarkowitz-NOAA

**Comment by EmilyMarkowitz-NOAA** [comment]
Couldn't agree more. In addition to comment as #19 , I'll add that more API-pull guidance can be found at https://afsc-gap-products.github.io/gap_products/content/foss-intro.html.
