### ISSUE TITLE
Repo website needs work

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [EmilyMarkowitz-NOAA/gap_public_data#19]
Some links go to just a map of survey areas with no links to move forward.  The main page doesn't have much there that specifically helps with getting/understanding our data.

Overall I don't see the website being useful until we do more work on it.  Maybe we should consider taking it down until it has more utility?

**Comment by EmilyMarkowitz-NOAA** [comment]
Couldn't agree more. 

This repository will soon be archived, actually. All of this code and documentation has been moved to the gap_products repo, which houses the code for the master production tables, tables shared with AKFIN, and FOSS. Documentation for the FOSS tables can be found at https://afsc-gap-products.github.io/gap_products/content/foss-intro.html. FOSS tables are now created on the GAP_PRODUCTS oracle schema and views for these tables are created on the RACEBASE_FOSS oracle schema.
