### ISSUE TITLE
query = list(srvy = "EBS") still returns AI table

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [EmilyMarkowitz-NOAA/gap_public_data#2]
I would like to narrow my queries to specific regions and am trying to get GOA tables only for a project. I tested out the region specificity by running the examples in the README.  `httr::get()` seems to return the same table regardless of what I put in the query list. Following the example in the README, this:
```{r}
res <- httr::GET(api_link)
data <- jsonlite::fromJSON(base::rawToChar(res$content))
head(data)
```
returns this:
![image](https://user-images.githubusercontent.com/73858992/176021589-378e1280-f8a0-4510-bb97-84bee511be99.png)

and this:
```{r}
res <- httr::GET(api_link, query = list(srvy = "EBS", year = 2018))
data <- jsonlite::fromJSON(base::rawToChar(res$content))
x <- data$items
head(x)
```
also returns the same thing:
![image](https://user-images.githubusercontent.com/73858992/176021775-503afcad-1e5c-40fb-a74e-0f0bb74b6a7c.png)

Shouldn't that `query` argument mean that `httr::get()` returns a table that is specific to your query? This may need to be fixed in the README.

Thank you for making these tables accessible! This is very helpful.

**Comment by EmilyMarkowitz-NOAA** [comment]
Thanks for this and sorry for the delay in getting back to you. I reached out to the FOSS team again and they said that this should be resolved in the next week or so. Feel free to ping me if this is still unresolved.

**Comment by EmilyMarkowitz-NOAA** [comment]
I have * sort of * figured it out. These [updated notes](https://github.com/afsc-gap-products/gap_public_data#connect-to-the-api-with-r) provide some solutions. I am not sure why the code used earlier didn't work, but hopefully this works better! Let me know if you have more examples to add to the readme as you investigate this.
