### ISSUE TITLE
some columns not returned via API

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [EmilyMarkowitz-NOAA/gap_public_data#5]
Emily, this is so amazing, thanks a ton.  I finally started working with it and love it, but ran into a few issues for my use case that are easy fixes:

- [x] Need hauljoin to be passed and it is not returned by API
- [x] Itis code is not returned by API
- [x] only start lat/lon was available by API, but we should return end lat/lon also\
- [x] Haul performance should perhaps be included as well (even though we already are removing "bad" tows)

**Comment by EmilyMarkowitz-NOAA** [comment]
Great notes! I will add these columns with the release of the 2022 data. Thanks for submitting an issue and let me know if there is anything else I can add!

**Comment by Lewis-Barnett-NOAA** [comment]
Thanks for working on this Emily.  The other task that comes to mind is how to toggle how to incorporate hauls with 0 catch for a given species, as requested by Ianelli in the data request repo

**Comment by EmilyMarkowitz-NOAA** [comment]
@Lewis-Barnett-NOAA - can you check that the `RACEBASE_FOSS.FOSS_CPUE_ZEROFILLED` oracle schema table has everything (columns, etc) you requested/need? The FOSS team will be re-pulling that data and implementing a patch that should show these columns on FOSS soon. Thanks!
