### ISSUE TITLE
API/query code in readme does not return all data

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [EmilyMarkowitz-NOAA/gap_public_data#8]
Related to Megsie's earlier comment, the code in the readme for accessing data by API is either incorrect or there is a problem with the API itself, as the example code to pull all the data only returns 25 records from two hauls on the 2002 AI survey

**Comment by EmilyMarkowitz-NOAA** [comment]
I reached out to the FOSS team again and they said the API should be fixed in the next week or so with a large patch they are pushing through. Sorry for the wait and thanks for your patience. Feel free to ping me if it is still unresolved.
